# Generated by Django 4.2.27 on 2026-02-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregates', '0001_initial'),
        ('indicators', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains')], default='equals', max_length=20)),
                ('match_value', models.JSONField(blank=True, null=True)),
                ('count_distinct', models.CharField(choices=[('respondent', 'Respondent'), ('interaction', 'Interaction')], default='respondent', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_derivation_rules', to=settings.AUTH_USER_MODEL)),
                ('output_indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivation_rule', to='indicators.indicator')),
                ('source_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivation_rule_sources', to='indicators.indicator')),
            ],
            options={
                'ordering': ['output_indicator__code'],
            },
        ),
    ]

