# Generated by Django 4.2.28 on 2026-03-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_expand_indicator_categories'),
        ('organizations', '0002_alter_organization_type'),
        ('projects', '0003_projectindicatororganizationtarget'),
        ('analysis', '0002_scheduledreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Fiscal year start (e.g. 2025 for FY 2025/26).')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_targets', to='organizations.organization')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_targets', to='indicators.indicator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_targets', to='projects.project')),
            ],
            options={
                'ordering': ['-year', 'quarter', 'project__name', 'coordinator__name', 'indicator__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='coordinatortarget',
            constraint=models.UniqueConstraint(fields=('project', 'coordinator', 'indicator', 'year', 'quarter'), name='uq_coordinator_target_scope_period'),
        ),
    ]
